name: doc_doc
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.2+1


environment:
  sdk: ">=3.4.1 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  get_it: ^7.7.0
  logger: ^2.3.0
  connectivity_plus: ^6.0.3
  fluttertoast: ^8.2.6
  intl: ^0.19.0
  permission_handler: ^11.3.1
  url_launcher: ^6.2.6
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  pretty_dio_logger: ^1.3.1
  json_annotation: ^4.9.0
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  build_runner: ^2.4.10
  json_serializable: ^6.8.0
  freezed_annotation: ^2.4.1

  freezed: ^2.5.2
  easy_localization: ^3.0.7
  firebase_core: ^2.32.0
  flutter_bloc: ^8.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/svgs/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
