default_platform(:android)

platform :android do
  desc "Lane For Android FireBase Distribution "
  lane :firebase_distribution do
  sh "flutter clean"
  sh "flutter build apk --release --flavor production -t lib/main_production.dart"
  firebase_app_distribution(
    app: "1:425291523484:android:b472285de121c0db309459",
    release_notes: "Welcome to FlutterFire. This is the release notes.",
    testers:"hmdy7486@gmail.com",
    # android_artifact_type:"APK",
    android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
    firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"]  )
  end
end
